language: ruby
rvm:
  - "2.3.1"
  - "jruby"
script:
  - bundle exec rspec --format documentation
notifications:
  email:
    recipients:
      - D&ENewsFrameworksTeam@bbc.co.uk
    on_failure: change
    on_success: never
